# Generated by Django 4.1 on 2024-01-22 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaqQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Question")),
                ("question_en", models.TextField(null=True, verbose_name="Question")),
                ("question_fi", models.TextField(null=True, verbose_name="Question")),
                ("answer", models.TextField(verbose_name="Answer")),
                ("answer_en", models.TextField(null=True, verbose_name="Answer")),
                ("answer_fi", models.TextField(null=True, verbose_name="Answer")),
                (
                    "hook",
                    models.SlugField(allow_unicode=True, max_length=255, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaqToInstanceLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Revision to display"
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.contentpage",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseinstance",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="faq.faqquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("instance", "question", "exercise")},
            },
        ),
    ]
