# Generated by Django 2.2.12 on 2020-11-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20201007_1444'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqquestion',
            name='exercise',
        ),
        migrations.CreateModel(
            name='FaqToInstanceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(blank=True, null=True, verbose_name='Revision to display')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentPage')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInstance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faq.FaqQuestion')),
            ],
            options={
                'unique_together': {('instance', 'question')},
            },
        ),
    ]
