# Generated by Django 4.1 on 2024-03-13 12:32

from django.db import migrations
from utils.management import get_prefixed_slug

def initialize_faqs(apps, schema_editor):
    FaqQuestion = apps.get_model("faq", "FaqQuestion")
    for faq in FaqQuestion.objects.all():
        link = faq.faqtoinstancelink_set.get_queryset().order_by("id").first()
        faq.origin = link and link.instance.course
        faq.slug = get_prefixed_slug(faq, faq.origin, "hook", translated=False)
        assert faq.slug is not None
        faq.save()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_guess_prefixes_generate_uuids"),
        ("faq", "0002_faqquestion_origin_faqquestion_slug"),
    ]

    operations = [
        migrations.RunPython(initialize_faqs)
    ]
