# Generated by Django 2.2.12 on 2020-11-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20201007_1444'),
        ('faq', '0002_auto_20201113_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqquestion',
            name='hook',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='faqtoinstancelink',
            unique_together={('instance', 'question', 'exercise')},
        ),
    ]
