# Generated by Django 4.1 on 2024-01-22 12:43

import django.contrib.postgres.fields
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("header", models.TextField(blank=True, default="")),
                ("footer", models.TextField(blank=True, default="")),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MossSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matches",
                    models.IntegerField(verbose_name="Number of matches to show"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[], max_length=32, verbose_name="Programming language"
                    ),
                ),
                (
                    "file_extensions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "exclude_filenames",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "exclude_subfolders",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=32),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.fileuploadexercise",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MossBaseFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fileinfo",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/opt/lovelace/upload"
                        ),
                        upload_to=utils.files.get_moss_basefile_path,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.fileuploadexercise",
                    ),
                ),
                (
                    "moss_settings",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher_tools.mosssettings",
                    ),
                ),
            ],
        ),
    ]
