# Generated by Django 2.0.2 on 2018-06-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('question_en', models.CharField(max_length=100, null=True, verbose_name='Question')),
                ('question_fi', models.CharField(max_length=100, null=True, verbose_name='Question')),
                ('question_type', models.CharField(choices=[('THUMB_FEEDBACK', 'Thumb feedback'), ('STAR_FEEDBACK', 'Star feedback'), ('MULTIPLE_CHOICE_FEEDBACK', 'Multiple choice feedback'), ('TEXTFIELD_FEEDBACK', 'Textfield feedback')], default='TEXTFIELD_FEEDBACK', max_length=28)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['question_type'],
            },
        ),
        migrations.CreateModel(
            name='ContentFeedbackUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerer_ip', models.GenericIPAddressField()),
                ('answer_date', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of when the user answered this feedback question')),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceFeedbackAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_en', models.TextField(null=True)),
                ('answer_fi', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceFeedbackUserAnswer',
            fields=[
                ('contentfeedbackuseranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.ContentFeedbackUserAnswer')),
                ('chosen_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.MultipleChoiceFeedbackAnswer')),
            ],
            options={
                'get_latest_by': 'answer_date',
            },
            bases=('feedback.contentfeedbackuseranswer',),
        ),
        migrations.CreateModel(
            name='StarFeedbackUserAnswer',
            fields=[
                ('contentfeedbackuseranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.ContentFeedbackUserAnswer')),
                ('rating', models.PositiveSmallIntegerField()),
            ],
            options={
                'get_latest_by': 'answer_date',
            },
            bases=('feedback.contentfeedbackuseranswer',),
        ),
        migrations.CreateModel(
            name='TextfieldFeedbackUserAnswer',
            fields=[
                ('contentfeedbackuseranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.ContentFeedbackUserAnswer')),
                ('answer', models.TextField()),
            ],
            options={
                'get_latest_by': 'answer_date',
            },
            bases=('feedback.contentfeedbackuseranswer',),
        ),
        migrations.CreateModel(
            name='ThumbFeedbackUserAnswer',
            fields=[
                ('contentfeedbackuseranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedback.ContentFeedbackUserAnswer')),
                ('thumb_up', models.BooleanField()),
            ],
            options={
                'get_latest_by': 'answer_date',
            },
            bases=('feedback.contentfeedbackuseranswer',),
        ),
        migrations.AddField(
            model_name='contentfeedbackuseranswer',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentPage'),
        ),
        migrations.AddField(
            model_name='contentfeedbackuseranswer',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseInstance'),
        ),
        migrations.AddField(
            model_name='contentfeedbackuseranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.ContentFeedbackQuestion'),
        ),
        migrations.AddField(
            model_name='contentfeedbackuseranswer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MultipleChoiceFeedbackQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'content multiple choice feedback question',
                'indexes': [],
            },
            bases=('feedback.contentfeedbackquestion',),
        ),
        migrations.CreateModel(
            name='StarFeedbackQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'content star feedback question',
                'indexes': [],
            },
            bases=('feedback.contentfeedbackquestion',),
        ),
        migrations.CreateModel(
            name='TextfieldFeedbackQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'content textfield feedback question',
                'indexes': [],
            },
            bases=('feedback.contentfeedbackquestion',),
        ),
        migrations.CreateModel(
            name='ThumbFeedbackQuestion',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'content thumb feedback question',
                'indexes': [],
            },
            bases=('feedback.contentfeedbackquestion',),
        ),
        migrations.AddField(
            model_name='multiplechoicefeedbackanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.MultipleChoiceFeedbackQuestion'),
        ),
    ]
