# Generated by Django 4.1 on 2024-03-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0006_rename_course_term_origin_alter_term_unique_together_and_more",
        ),
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentfeedbackquestion",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.course",
            ),
        ),
    ]
