# Generated by Django 4.1 on 2024-03-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assessmentsheet",
            old_name="course",
            new_name="origin",
        ),
        migrations.AddField(
            model_name="assessmentsheet",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, null=True, max_length=255, unique=True
            ),
            preserve_default=False,
        ),
    ]
