# Generated by Django 4.1 on 2024-03-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessment", "0004_initialize_prefxed_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentsheet",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, null=False, max_length=255, unique=True
            ),
        ),
    ]
