# Generated by Django 5.2.5 on 2025-11-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_finalize_slugfields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentbullet',
            unique_together={('sheet', 'section', 'ordinal_number')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsection',
            unique_together={('sheet', 'ordinal_number')},
        ),
    ]
