# Generated by Django 5.2.5 on 2025-11-17 12:45

from django.db import migrations

def renumerate_sections(apps, schema_editor):
    AssessmentSheet = apps.get_model("assessment", "assessmentsheet")
    for sheet in AssessmentSheet.objects.all():
        sections = sheet.assessmentsection_set.get_queryset()
        needfix = False
        for section in sections:
            if sections.exclude(id=section.id).filter(ordinal_number=section.ordinal_number).exists():
                needfix = True
                break
        if needfix:
            for i, section in enumerate(sections.order_by("ordinal_number"), 1):
                section.ordinal_number = i
                section.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_finalize_slugfields'),
    ]

    operations = [
        migrations.RunPython(renumerate_sections)
    ]
