# Generated by Django 5.2.5 on 2025-11-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_assessmentbullet_unique_together_and_more'),
        ('courses', '0036_alter_courseinstance_ws_server_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmenttoexerciselink',
            unique_together={('instance', 'exercise')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentbullet',
            unique_together={('sheet', 'section', 'ordinal_number')},
        ),
        migrations.AlterUniqueTogether(
            name='assessmentsection',
            unique_together={('sheet', 'ordinal_number')},
        ),
    ]
