# Generated by Django 5.2.15 on 2026-08-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerlessTask',
            fields=[
            ],
            options={
                'verbose_name': 'answerless task',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.contentpage',),
        ),
        migrations.CreateModel(
            name='AnswerlessEntry',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.useranswer')),
                ('note', models.TextField(blank=True, default='')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answerless.answerlesstask')),
            ],
            bases=('courses.useranswer',),
        ),
    ]
