# Generated by Django 4.1 on 2024-01-22 12:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultipleQuestionExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField(blank=True, null=True)),
                ("questions", models.JSONField()),
                ("open_from", models.DateTimeField(verbose_name="Answerable from")),
                ("open_to", models.DateTimeField(verbose_name="Answerable until")),
            ],
        ),
        migrations.CreateModel(
            name="MultipleQuestionExam",
            fields=[],
            options={
                "verbose_name": "multiple question exam",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("courses.contentpage",),
        ),
        migrations.CreateModel(
            name="UserMultipleQuestionExamAnswer",
            fields=[
                (
                    "useranswer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="courses.useranswer",
                    ),
                ),
                ("answers", models.JSONField()),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multiexam.multiplequestionexamattempt",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multiexam.multiplequestionexam",
                    ),
                ),
            ],
            bases=("courses.useranswer",),
        ),
        migrations.AddField(
            model_name="multiplequestionexamattempt",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="multiexam.multiplequestionexam",
            ),
        ),
        migrations.AddField(
            model_name="multiplequestionexamattempt",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.courseinstance"
            ),
        ),
        migrations.AddField(
            model_name="multiplequestionexamattempt",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ExamQuestionPool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fileinfo",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/opt/lovelace/upload"
                        ),
                        upload_to=utils.files.get_testfile_path,
                    ),
                ),
                (
                    "fileinfo_en",
                    models.FileField(
                        max_length=255,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/opt/lovelace/upload"
                        ),
                        upload_to=utils.files.get_testfile_path,
                    ),
                ),
                (
                    "fileinfo_fi",
                    models.FileField(
                        max_length=255,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/opt/lovelace/upload"
                        ),
                        upload_to=utils.files.get_testfile_path,
                    ),
                ),
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="multiexam.multiplequestionexam",
                    ),
                ),
            ],
        ),
    ]
