# Generated by Django 5.0.6 on 2025-04-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiexam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="multiplequestionexamattempt",
            name="key",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
