# Generated by Django 2.0.2 on 2019-10-22 11:39

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20190927_1345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExerciseAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('date_answered', models.DateTimeField()),
                ('given_answer', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExerciseBackendCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('command_en', models.TextField(null=True)),
                ('command_fi', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'routine exercise backend command',
            },
        ),
        migrations.CreateModel(
            name='RoutineExerciseBackendFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('fileinfo', models.FileField(max_length=255, storage=django.core.files.storage.FileSystemStorage(location='/home/enk/lovelace-ex/upload/'), upload_to=utils.files.get_testfile_path)),
            ],
            options={
                'verbose_name': 'routine exercise backend file',
                'verbose_name_plural': 'routine exercise backend files',
            },
        ),
        migrations.CreateModel(
            name='RoutineExerciseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('language_code', models.CharField(max_length=7)),
                ('question_class', models.PositiveIntegerField()),
                ('date_generated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoutineExerciseTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_fi', models.TextField(null=True)),
                ('question_class', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'routine exercise template',
                'verbose_name_plural': 'routine exercise templates',
            },
        ),
        migrations.CreateModel(
            name='RoutineExercise',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name': 'routine exercise',
                'indexes': [],
            },
            bases=('courses.contentpage',),
        ),
        migrations.AddField(
            model_name='routineexercisetemplate',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_exercise.RoutineExercise'),
        ),
        migrations.AddField(
            model_name='routineexercisequestion',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_exercise.RoutineExercise'),
        ),
        migrations.AddField(
            model_name='routineexercisequestion',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseInstance'),
        ),
        migrations.AddField(
            model_name='routineexercisequestion',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routine_exercise.RoutineExerciseTemplate'),
        ),
        migrations.AddField(
            model_name='routineexercisequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routineexercisebackendfile',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_exercise.RoutineExercise'),
        ),
        migrations.AddField(
            model_name='routineexercisebackendcommand',
            name='exercise',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routine_exercise.RoutineExercise'),
        ),
        migrations.AddField(
            model_name='routineexerciseanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routine_exercise.RoutineExerciseQuestion'),
        ),
    ]
