# Generated by Django 4.1 on 2024-01-22 12:43

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import utils.files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutineExercise",
            fields=[],
            options={
                "verbose_name": "routine exercise",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("courses.contentpage",),
        ),
        migrations.CreateModel(
            name="RoutineExerciseTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("content_en", models.TextField(null=True)),
                ("content_fi", models.TextField(null=True)),
                ("question_class", models.PositiveIntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine_exercise.routineexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "routine exercise template",
                "verbose_name_plural": "routine exercise templates",
            },
        ),
        migrations.CreateModel(
            name="RoutineExerciseQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField(null=True)),
                ("language_code", models.CharField(max_length=7)),
                ("question_class", models.PositiveIntegerField()),
                ("generated_json", models.JSONField()),
                ("date_generated", models.DateTimeField()),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine_exercise.routineexercise",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.courseinstance",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="routine_exercise.routineexercisetemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineExerciseBackendFile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                (
                    "fileinfo",
                    models.FileField(
                        max_length=255,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/opt/lovelace/upload"
                        ),
                        upload_to=utils.files.get_testfile_path,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine_exercise.routineexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "routine exercise backend file",
                "verbose_name_plural": "routine exercise backend files",
            },
        ),
        migrations.CreateModel(
            name="RoutineExerciseBackendCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("command", models.TextField()),
                ("command_en", models.TextField(null=True)),
                ("command_fi", models.TextField(null=True)),
                (
                    "exercise",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine_exercise.routineexercise",
                    ),
                ),
            ],
            options={
                "verbose_name": "routine exercise backend command",
            },
        ),
        migrations.CreateModel(
            name="RoutineExerciseAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("correct", models.BooleanField(null=True)),
                ("answer_date", models.DateTimeField()),
                ("given_answer", models.TextField(blank=True)),
                ("task_id", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine_exercise.routineexercisequestion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoutineExerciseProgress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("progress", models.CharField(max_length=255)),
                ("progress_en", models.CharField(max_length=255, null=True)),
                ("progress_fi", models.CharField(max_length=255, null=True)),
                (
                    "points",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("max_points", models.PositiveIntegerField(default=1)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routine_exercise.routineexercise",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.courseinstance",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("exercise", "instance", "user")},
            },
        ),
    ]
