# Generated by Django 2.0.2 on 2019-10-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine_exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routineexercisequestion',
            name='revision',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
