# Generated by Django 4.1 on 2024-02-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine_exercise", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routineexercisetemplate",
            name="variant",
            field=models.PositiveIntegerField(
                null=True,
            ),
            preserve_default=False,
        ),
    ]
