# Generated by Django 4.1 on 2024-02-23 11:15

from django.db import migrations

def re_save_templates(apps, schema_editor):
    RoutineExerciseTemplate = apps.get_model("routine_exercise", "RoutineExerciseTemplate")
    for template in RoutineExerciseTemplate.objects.all():
        if template.variant is None:
            previous = RoutineExerciseTemplate.objects.filter(
                exercise=template.exercise,
                question_class=template.question_class
            ).exclude(variant=None).order_by("-variant").first()
            if previous and previous.variant is not None:
                template.variant = previous.variant + 1
            else:
                template.variant = 0
            template.save()


class Migration(migrations.Migration):
    dependencies = [
        ("routine_exercise", "0002_routineexercisetemplate_variant"),
    ]

    operations = [
        migrations.RunPython(re_save_templates)
    ]
