# Generated by Django 2.0.2 on 2019-10-23 15:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_exercise', '0002_auto_20191023_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='routineexercisequestion',
            name='generated_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{}'),
            preserve_default=False,
        ),
    ]
