# Generated by Django 2.0.2 on 2019-11-01 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190927_1345'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routine_exercise', '0003_routineexercisequestion_generated_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineExerciseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('progress', models.CharField(max_length=255)),
                ('progress_en', models.CharField(max_length=255, null=True)),
                ('progress_fi', models.CharField(max_length=255, null=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine_exercise.RoutineExercise')),
                ('instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.CourseInstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='routineexerciseanswer',
            name='correct',
            field=models.NullBooleanField(),
        ),
    ]
