# Generated by Django 4.1 on 2024-02-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routine_exercise", "0003_calc_variants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routineexercisetemplate",
            name="variant",
            field=models.PositiveIntegerField(null=False),
            preserve_default=False,
        ),
    ]
