# Generated by Django 5.2.5 on 2025-11-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_exercise', '0004_finalize_variant_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routineexercisebackendfile',
            unique_together={('exercise', 'filename')},
        ),
        migrations.AlterUniqueTogether(
            name='routineexercisetemplate',
            unique_together={('exercise', 'variant', 'question_class')},
        ),
    ]
