# Generated by Django 5.2.5 on 2026-05-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine_exercise', '0005_alter_routineexercisebackendfile_unique_together_and_more'),
    ]

    operations = [
    ]
