# Generated by Django 5.2.5 on 2026-05-06 15:05

from django.db import migrations

def standardize_variants(apps, schema_editor):
    ContentPage = apps.get_model("courses", "contentpage")
    RoutineExerciseTemplate = apps.get_model("routine_exercise", "routineexercisetemplate")

    for page in ContentPage.objects.all():
        if page.content_type == "ROUTINE_EXERCISE":
            templates = RoutineExerciseTemplate.objects.filter(exercise=page)
            for qc in templates.distinct("question_class").values_list("question_class", flat=True):
                variants = templates.filter(question_class=qc).order_by("variant")
                for i, template in enumerate(variants, start=1):
                    template.variant = i
                    template.save()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_exercise', '0005_alter_routineexercisebackendfile_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(standardize_variants)
    ]
