# Generated by Django 5.2.15 on 2026-08-05 15:25

import json
from django.db import migrations
from reversion.models import Version
from django.contrib.contenttypes.models import ContentType


def sync_unique_keys(apps, schema_editor):
    ContentPage = apps.get_model("courses", "contentpage")
    RoutineExerciseTemplate = apps.get_model("routine_exercise", "routineexercisetemplate")
    template_type_id = ContentType.objects.get(model=RoutineExerciseTemplate._meta.model_name).id

    for page in ContentPage.objects.all():
        if page.content_type == "ROUTINE_EXERCISE":
            for version in Version.objects.get_for_object(page):
                for tmpl_ver in version.revision.version_set.filter(content_type=template_type_id):
                    data = json.loads(tmpl_ver.serialized_data)[0]
                    try:
                        current = RoutineExerciseTemplate.objects.get(pk=data["pk"])
                    except RoutineExerciseTemplate.DoesNotExist:
                        continue
                    data["fields"]["question_class"] = current.question_class
                    data["fields"]["variant"] = current.variant
                    tmpl_ver.serialized_data = json.dumps([data])
                    tmpl_ver.save()


class Migration(migrations.Migration):

    dependencies = [
        ('routine_exercise', '0006_standardize_variants'),
    ]

    operations = [
        migrations.RunPython(sync_unique_keys)

    ]
