# Generated by Django 4.1 on 2024-05-22 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentTaskStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField(blank=True, null=True)),
                ("total_answers", models.PositiveIntegerField(default=0)),
                ("tries_until_correct", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("before_deadline", models.PositiveIntegerField(null=True)),
                ("after_deadline", models.PositiveIntegerField(null=True)),
                ("same_answers", models.PositiveIntegerField(default=0)),
                ("correct_before_dl", models.BooleanField(default=False)),
                ("first_answer", models.DateTimeField(null=True)),
                ("first_correct", models.DateTimeField(null=True)),
                ("last_answer", models.DateTimeField(null=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseinstance",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskSummary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField(blank=True, null=True)),
                ("total_answers", models.PositiveIntegerField(default=0)),
                ("total_tries", models.PositiveIntegerField(default=0)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("correct_by_total", models.PositiveIntegerField(default=0)),
                ("correct_by_before_dl", models.PositiveIntegerField(default=0)),
                ("correct_by_after_dl", models.PositiveIntegerField(default=0)),
                ("tries_avg", models.FloatField(default=0.0)),
                ("tries_median", models.PositiveIntegerField(default=0.0)),
                ("tries_25p", models.PositiveIntegerField(default=0)),
                ("tries_75p", models.PositiveIntegerField(default=0)),
                ("time_avg", models.DurationField(default=datetime.timedelta(0))),
                ("time_median", models.DurationField(default=datetime.timedelta(0))),
                ("time_25p", models.DurationField(default=datetime.timedelta(0))),
                ("time_75p", models.DurationField(default=datetime.timedelta(0))),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseinstance",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.contentpage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "tasks_answered",
                    models.ManyToManyField(blank=True, to="stats.studenttaskstats"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="studenttaskstats",
            name="study_sessions",
            field=models.ManyToManyField(blank=True, to="stats.studysession"),
        ),
        migrations.AddField(
            model_name="studenttaskstats",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.contentpage"
            ),
        ),
    ]
