# Generated by Django 2.0.2 on 2019-04-08 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_contentpage_evaluation_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTaskStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(blank=True, null=True)),
                ('total_answers', models.PositiveIntegerField()),
                ('correct_answers', models.PositiveIntegerField()),
                ('before_deadline', models.PositiveIntegerField(null=True)),
                ('after_deadline', models.PositiveIntegerField(null=True)),
                ('same_answers', models.PositiveIntegerField()),
                ('correct_before_dl', models.BooleanField(default=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.CourseInstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('tasks_answered', models.ManyToManyField(blank=True, to='stats.StudentTaskStats')),
            ],
        ),
        migrations.AddField(
            model_name='studenttaskstats',
            name='study_sessions',
            field=models.ManyToManyField(blank=True, to='stats.StudySession'),
        ),
        migrations.AddField(
            model_name='studenttaskstats',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.ContentPage'),
        ),
    ]
