# Generated by Django 2.0.2 on 2019-04-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttaskstats',
            name='same_answers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
