# Generated by Django 4.1 on 2024-02-07 10:19

import django.core.files.storage
from django.db import migrations, models
import utils.files


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codeinputexerciseanswer",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="codereplaceexerciseanswer",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="codereplaceexercisereplacement",
            name="answer",
        ),
        migrations.RemoveField(
            model_name="codereplaceexercisereplacement",
            name="target",
        ),
        migrations.RemoveField(
            model_name="usercodereplaceexerciseanswer",
            name="exercise",
        ),
        migrations.RemoveField(
            model_name="usercodereplaceexerciseanswer",
            name="useranswer_ptr",
        ),
        migrations.DeleteModel(
            name="CodeInputExercise",
        ),
        migrations.DeleteModel(
            name="CodeReplaceExercise",
        ),
        migrations.DeleteModel(
            name="CodeInputExerciseAnswer",
        ),
        migrations.DeleteModel(
            name="CodeReplaceExerciseAnswer",
        ),
        migrations.DeleteModel(
            name="CodeReplaceExerciseReplacement",
        ),
        migrations.DeleteModel(
            name="UserCodeReplaceExerciseAnswer",
        ),
    ]
