# Generated by Django 4.1 on 2024-02-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_remove_codeinputexerciseanswer_exercise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentgroup",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Group name"),
        ),
        migrations.AlterField(
            model_name="termalias",
            name="term",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.term",
            ),
        ),
    ]
