# Generated by Django 4.1 on 2024-02-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_remove_fileexercisetestincludefile_file_settings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileexercisetestincludefile",
            name="file_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.includefilesettings",
            ),
        ),
        migrations.AlterField(
            model_name="instanceincludefiletoexerciselink",
            name="file_settings",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.includefilesettings",
            ),
        ),
    ]
