# Generated by Django 4.1 on 2024-03-13 12:30

from django.db import migrations, models
from utils.management import get_prefixed_slug

# there is no feasible way to connect calendars back to courses
# so we're going to assume all existing calendars are orphans
def initialize_calendars(apps, schema_editor):
    Calendar = apps.get_model("courses", "Calendar")
    for calendar in Calendar.objects.all():
        calendar.slug = get_prefixed_slug(calendar, calendar.origin, "name", translated=False)
        assert calendar.slug is not None
        calendar.save()

def initialize_media(apps, schema_editor):
    CourseMedia = apps.get_model("courses", "CourseMedia")
    for media in CourseMedia.objects.all():
        link = media.coursemedialink_set.order_by("id").first()
        media.origin = link and link.instance.course
        media.slug = get_prefixed_slug(media, media.origin, "name", translated=False)
        assert media.slug is not None
        media.save()

def initialize_instance_include_files(apps, schema_editor):
    InstanceIncludeFile = apps.get_model("courses", "InstanceIncludeFile")
    for ifile in InstanceIncludeFile.objects.all():
        ifile.slug = get_prefixed_slug(ifile, ifile.course, "default_name")
        assert ifile.slug is not None
        ifile.save()


def initialize_terms(apps, schema_editor):
    Term = apps.get_model("courses", "Term")
    for term in Term.objects.all():
        term.slug = get_prefixed_slug(term, term.origin, "name")
        assert term.slug is not None
        term.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0007_guess_prefixes_generate_uuids",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="includefilesettings",
            name="export_id",
            field=models.UUIDField(editable=False, unique=True, null=False),
        ),

        migrations.RunPython(initialize_calendars),
        migrations.RunPython(initialize_media),
        migrations.RunPython(initialize_instance_include_files),
        migrations.RunPython(initialize_terms),
    ]
