# Generated by Django 4.1 on 2024-03-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_initialize_prefixed_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, null=False, max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="coursemedia",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, null=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="instanceincludefile",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, null=False, max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="term",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, null=False, max_length=255, unique=True
            ),
        ),
    ]

