# Generated by Django 4.1 on 2024-03-14 14:18

from django.db import migrations, models
import uuid

def generate_uuids(apps, schema_editor):
    FileExerciseTestIncludeFile = apps.get_model("courses", "fileexercisetestincludefile")
    for i_f in FileExerciseTestIncludeFile.objects.all():
        i_f.export_id = uuid.uuid4()
        i_f.save()
    TermTag = apps.get_model("courses", "termtag")
    for tag in TermTag.objects.all():
        tag.export_id = uuid.uuid4()
        tag.save()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_termtag_includefile_export_id"),
    ]

    operations = [
        migrations.RunPython(generate_uuids),
    ]
