# Generated by Django 4.1 on 2024-03-14 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_termtag_export_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileexercisetestincludefile",
            name="export_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
