# Generated by Django 4.1 on 2024-05-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_coursemedia_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='Student ID'),
        ),
    ]
