# Generated by Django 5.0.6 on 2024-08-08 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0014_alter_userprofile_student_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="textfieldexerciseanswer",
            name="ordinal",
            field=models.PositiveIntegerField(null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fileexercisetestincludefile",
            name="export_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="includefilesettings",
            name="export_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="termtag",
            name="export_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
