# Generated by Django 5.0.6 on 2024-08-08 15:02

from django.db import migrations


def answer_ordinals(apps, schema_editor):
    TextfieldExerciseAnswer = apps.get_model("courses", "TextfieldExerciseAnswer")
    MultipleChoiceExerciseAnswer = apps.get_model("courses", "MultipleChoiceExerciseAnswer")
    CheckboxExerciseAnswer = apps.get_model("courses", "CheckboxExerciseAnswer")

    for model in [TextfieldExerciseAnswer, MultipleChoiceExerciseAnswer, CheckboxExerciseAnswer]:
        for answer in model.objects.all():
            if answer.ordinal is None:
                previous = model.objects.filter(
                    exercise=answer.exercise,
                ).exclude(ordinal=None).order_by("-ordinal").first()
                if previous and previous.ordinal is not None:
                    answer.ordinal = previous.ordinal + 1
                else:
                    answer.ordinal = 1
                answer.save()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_textfieldexerciseanswer_ordinal_and_more"),
    ]

    operations = [
        migrations.RunPython(answer_ordinals)
    ]

