# Generated by Django 5.0.6 on 2024-08-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0016_calc_textfield_answer_ordinals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textfieldexerciseanswer",
            name="ordinal",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="multiplechoiceexerciseanswer",
            name="ordinal",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="checkboxexerciseanswer",
            name="ordinal",
            field=models.PositiveIntegerField(),
        ),
    ]
