# Generated by Django 5.0.6 on 2024-11-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0020_evaluation_comment_evaluation_suspect"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=64, verbose_name="Message title"),
                ),
                (
                    "title_en",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Message title"
                    ),
                ),
                (
                    "title_fi",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Message title"
                    ),
                ),
                ("content", models.TextField(verbose_name="Message content")),
                (
                    "content_en",
                    models.TextField(null=True, verbose_name="Message content"),
                ),
                (
                    "content_fi",
                    models.TextField(null=True, verbose_name="Message content"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseinstance",
                    ),
                ),
            ],
        ),
    ]
