# Generated by Django 5.0.6 on 2024-11-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_coursemessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unread_messages",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Unread message count"
            ),
        ),
    ]
