# Generated by Django 5.0.6 on 2024-11-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0022_userprofile_unread_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="data_policy",
            field=models.CharField(
                choices=[
                    ("UNSELECTED", "Not selected"),
                    ("STANDARD", "Standard policy"),
                    ("RETAIN", "Retain my data"),
                ],
                default="UNSELECTED",
                max_length=10,
                verbose_name="Data retention preference",
            ),
        ),
    ]
