# Generated by Django 5.0.6 on 2025-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_userprofile_completed_userprofile_dyslexic_fonts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                choices=[("en", "English"), ("fi", "suomi")],
                default=None,
                null=True,
                verbose_name="Communication language",
            ),
        ),
    ]
