# Generated by Django 5.0.6 on 2025-02-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_userprofile_language_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='lock_cancel',
            field=models.BooleanField(default=False, verbose_name='Lock canceling as well'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='lock_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reservation lock time (hours)'),
        ),
    ]
