# Generated by Django 5.0.6 on 2025-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0026_calendar_lock_cancel_calendar_lock_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextfieldWidgetSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rows", models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name="contentpage",
            name="answer_widget",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
