# Generated by Django 5.0.6 on 2025-04-29 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0027_textfieldwidgetsettings_contentpage_answer_widget"),
    ]

    operations = [
        migrations.AddField(
            model_name="textfieldwidgetsettings",
            name="content",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.contentpage",
            ),
        ),
        migrations.AddField(
            model_name="textfieldwidgetsettings",
            name="instance",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstance",
            ),
            preserve_default=False,
        ),
    ]
