# Generated by Django 5.2.1 on 2025-06-05 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_textfieldwidgetsettings_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='embedded_pages',
            field=models.ManyToManyField(blank=True, through='courses.EmbeddedLink', through_fields=('parent', 'embedded_page', 'instance'), to='courses.contentpage'),
        ),
        migrations.AlterField(
            model_name='courseinstance',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, through='courses.CourseEnrollment', through_fields=('instance', 'student'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instanceincludefile',
            name='exercises',
            field=models.ManyToManyField(blank=True, through='courses.InstanceIncludeFileToExerciseLink', through_fields=('include_file', 'exercise'), to='courses.contentpage'),
        ),
    ]
