# Generated by Django 5.2.1 on 2025-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_contentpage_embedded_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textfieldwidgetsettings',
            name='key_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='textfieldwidgetsettings',
            unique_together={('key_slug', 'instance')},
        ),
        migrations.RemoveField(
            model_name='textfieldwidgetsettings',
            name='content',
        ),
    ]
