# Generated by Django 5.2.5 on 2025-09-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_textfieldwidgetsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textfieldwidgetsettings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='textfieldwidgetsettings',
            name='course',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfieldwidgetsettings',
            name='name',
            field=models.CharField(default='tba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textfieldwidgetsettings',
            name='slug',
            field=models.SlugField(default='tba', max_length=255),
            preserve_default=False,
        ),
    ]
