# Generated by Django 5.2.5 on 2025-09-01 15:37

from django.db import migrations
from utils.management import get_prefixed_slug

def refactor_data(apps, schema_editor):
    TextfieldWidgetSettings = apps.get_model("courses", "textfieldwidgetsettings")
    for model_inst in TextfieldWidgetSettings.objects.all():
        model_inst.course = model_inst.instance.course
        model_inst.name = model_inst.key_slug
        model_inst.slug = get_prefixed_slug(
            model_inst, model_inst.course, "name", translated=False
        )
        if not TextfieldWidgetSettings.objects.filter(
            course=model_inst.course, slug=model_inst.slug
        ).exists():
            model_inst.save()
        else:
            model_inst.delete()



class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_textfieldwidgetsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(refactor_data),
    ]
