# Generated by Django 5.2.5 on 2025-09-01 15:39

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_migrate_widget_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfieldwidgetsettings',
            name='course',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='courses.course'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textfieldwidgetsettings',
            name='name',
            field=models.CharField(
                max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textfieldwidgetsettings',
            name='slug',
            field=models.SlugField(
                max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='textfieldwidgetsettings',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='textfieldwidgetsettings',
            name='key_slug',
        ),
    ]
