# Generated by Django 5.2.5 on 2025-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_finalize_widget_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='ws_server',
            field=models.CharField(
                blank=True, null=True, max_length=255, verbose_name='WebSocket server address.'
            ),
        ),
    ]
