# Generated by Django 5.2.5 on 2025-11-07 12:00
from collections import defaultdict
import json
import re
from django.conf import settings
from django.core.paginator import Paginator
from django.db import migrations
from utils.management import get_prefixed_slug

def guess_origins(page):
    ContentGraph = apps.get_model("courses", "contentgraph")
    ContentPage = apps.get_model("courses", "contentpage")
    CourseMedia = apps.get_model("courses", "coursemedia")
    CourseMediaLink = apps.get_model("courses", "coursemedialink")
    EmbeddedLink = apps.get_model("courses", "embeddedlink")

    for page in ContentPage.objects.all():
        if page.origin:
            continue

        if cgs := ContentGraph.objects.filter(content=page).order_by("id"):
            page.origin = cgs.first().instance.course
        elif embeds := EmbeddedLink.objects.filter(embedded_page=page).order_by("id"):
            page.origin = embeds.first().instance.course
        else:
            continue

        page.save()

    for media in CourseMedia.objects.all():
        if not media.origin:
            if links := CourseMediaLink.objects.filter(media=media).order_by("id"):
                page.origin = links.first().instance.course

        media.save(regen_cache=False)


def refactor_slugs(apps, schema_editor):
    Calendar = apps.get_model("courses", "calendar")
    ContentPage = apps.get_model("courses", "contentpage")
    Term = apps.get_model("courses", "term")
    TermLink = apps.get_model("courses", "termlink")
    Version = apps.get_model("reversion", "version")

    all_replaces = {}
    updated_slugs = []

    # Page slug replacements
    for page in ContentPage.objects.all().order_by("-name"):

        old_ref = page.slug
        new_ref = get_prefixed_slug(page, page.origin, "name")
        if old_ref == new_ref:
            continue

        page.slug = new_ref
        page.save()

        for version in Version.objects.get_for_object(page):
            data = json.loads(version.serialized_data)
            data[0]["fields"]["slug"] = new_ref
            version.serialized_data = json.dumps(data)
            version.save()

        # Termlink replaces can be done immediately
        for termlink in TermLink.objects.filter(url__startswith=old_ref):
            for lang_code, _ in settings.LANGUAGES:
                link = getattr(termlink, f"url_{lang_code}", "")
                if link:
                    setattr(termlink, f"url_{lang_code}", link.replace(old_ref, new_ref))
            termlink.save()

            for version in Version.objects.get_for_object(termlink):
                data = json.loads(version.serialized_data)
                for lang_code, _ in settings.LANGUAGES:
                    link = data[0]["fields"].get(f"url_{lang_code}")
                    if link:
                        data[0]["fields"][f"url_{lang_code}"] = link.replace(old_ref, new_ref)
                version.serialized_data = json.dumps(data)
                version.save()

        # dl tag
        old_dl_tag = f"[!dl={old_ref}!]"
        new_dl_tag = f"[!dl={new_ref}!]"

        # assessment tag
        old_as_tag = f"<!assessment={old_ref}>"
        new_as_tag = f"<!assessment={new_ref}>"

        # link tags
        old_link_tag = f"[[{old_ref}"
        new_link_tag = f"[[{new_ref}"

        old_emb_tag = f"<!page={old_ref}>"
        new_emb_tag = f"<!page={new_ref}>"

        tags = [
            (old_dl_tag, new_dl_tag),
            (old_as_tag, new_as_tag),
            (old_emb_tag, new_emb_tag),
            (old_link_tag, new_link_tag)
        ]
        all_replaces.update(tags)

    term_replaces = defaultdict(dict)
    term_keys = []

    # Term slug replacements
    for term in Term.objects.all():
        for lang_code, _ in settings.LANGUAGES:
            lang_name = getattr(term, f"name_{lang_code}", "")
            if not lang_name:
                continue

            old_tag = f"[!term={lang_name}!]"
            new_tag = f"[!term={term.slug}!]"
            term_replaces[term.origin.prefix][old_tag] = new_tag
            term_keys.append(re.escape(old_tag))


    # Calendar slug replacements
    for calendar in Calendar.objects.all():
        old_tag = f"<!calendar={calendar.name}>"
        new_tag = f"<!calendar={calendar.slug}>"
        all_replaces[old_tag] = new_tag

    File = apps.get_model("courses", "File")
    Image = apps.get_model("courses", "Image")
    VideoLink = apps.get_model("courses", "VideoLink")

    for mediafile in File.objects.all():
        old_ref = mediafile.name
        new_ref = mediafile.slug

        old_emb_tag = f"<!file={old_ref}"
        new_emb_tag = f"<!file={new_ref}"

        old_script_tag = f"script={old_ref}"
        new_script_tag = f"script={new_ref}"

        old_style_tag = f"style={old_ref}"
        new_style_tag = f"style={new_ref}"

        old_flink = f"[[file:{old_ref}"
        new_flink = f"[[file:{new_ref}"

        tags = [
            (old_emb_tag, new_emb_tag),
            (old_script_tag, new_script_tag),
            (old_style_tag, new_style_tag),
            (old_flink, new_flink),
        ]
        all_replaces.update(tags)

    for image in Image.objects.all():
        old_ref = image.name
        new_ref = image.slug

        old_emb_tag = f"<!image={old_ref}"
        new_emb_tag = f"<!image={new_ref}"
        all_replaces[old_emb_tag] = new_emb_tag

    keys = [re.escape(key) for key in sorted(all_replaces, key=len, reverse=True)]

    pattern = re.compile("|".join(keys + term_keys))

    paginator = Paginator(ContentPage.objects.all(), 10)

    for page in paginator.page_range:
        print(f"Processing page {page} / {paginator.num_pages}")

        for container in paginator.page(page).object_list.iterator():

            def key_replace(matchobj):
                try:
                    return all_replaces[matchobj.group(0)]
                except KeyError:
                    prefix = container.origin and container.origin.prefix
                    return term_replaces[prefix].get(
                        matchobj.group(0), "null-missing-term"
                    )

            for lang_code, _ in settings.LANGUAGES:
                content = getattr(container, f"content_{lang_code}", "")
                content = pattern.sub(key_replace, content)
                setattr(container, f"content_{lang_code}", content)
            container.save()

            for version in Version.objects.get_for_object(container):
                data = json.loads(version.serialized_data)
                for lang_code, _ in settings.LANGUAGES:
                    content = data[0]["fields"].get(f"content_{lang_code}", "")
                    content = pattern.sub(key_replace, content)
                    data[0]["fields"][f"content_{lang_code}"] = content
                version.serialized_data = json.dumps(data)
                version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_courseinstance_ws_server'),
    ]

    operations = [
        migrations.RunPython(guess_origins),
        migrations.RunPython(refactor_slugs),
    ]
