# Generated by Django 5.2.5 on 2025-11-07 12:00
from collections import defaultdict
import json
import re
from django.conf import settings
from django.core.paginator import Paginator
from django.db import migrations
from reversion.models import Version
from utils.management import get_prefixed_slug

def guess_origins(apps, schema_editor):
    ContentGraph = apps.get_model("courses", "contentgraph")
    ContentPage = apps.get_model("courses", "contentpage")
    CourseMedia = apps.get_model("courses", "coursemedia")
    CourseMediaLink = apps.get_model("courses", "coursemedialink")
    EmbeddedLink = apps.get_model("courses", "embeddedlink")
    Calendar = apps.get_model("courses", "calendar")
    Course = apps.get_model("courses", "course")

    print()

    print("    Guessing page origins")
    pages = list(ContentPage.objects.all())
    for page in pages:
        if not page.slug:
            page.delete()
            continue

        if page.origin:
            continue

        if cgs := ContentGraph.objects.filter(content=page).order_by("id"):
            page.origin = cgs.first().instance.course
        elif embeds := EmbeddedLink.objects.filter(embedded_page=page).order_by("id"):
            page.origin = embeds.first().instance.course
        else:
            continue

        page.save()

    print("    Guessing media origins")
    for media in CourseMedia.objects.all():
        if not media.origin:
            if links := CourseMediaLink.objects.filter(media=media).order_by("id"):
                media.origin = links.first().instance.course

        media.slug = get_prefixed_slug(media, media.origin, "name", translated=False)
        media.save()

    prefix_map = {}
    for course in Course.objects.all():
        prefix_map[course.prefix] = course

    print("    Guessing calendar origins")
    for calendar in Calendar.objects.all():
        calendar_prefix = calendar.name.split("-", 1)[0]
        if matching_course := prefix_map.get(calendar_prefix):
            calendar.origin = matching_course
        else:
            for page in pages:
                for lang_code, _ in settings.LANGUAGES:
                    if calendar.name in getattr(page, f"content_{lang_code}"):
                        calendar.origin = page.origin
        calendar.save()


def refactor_slugs(apps, schema_editor):
    Calendar = apps.get_model("courses", "calendar")
    ContentPage = apps.get_model("courses", "contentpage")
    Term = apps.get_model("courses", "term")
    TermLink = apps.get_model("courses", "termlink")
    # Version = apps.get_model("reversion", "version")

    all_replaces = {}
    updated_slugs = []

    # Page slug replacements
    print("    Preparing prefixed page slugs")
    for page in ContentPage.objects.all().order_by("-name"):

        old_ref = page.slug
        new_ref = get_prefixed_slug(page, page.origin, "name")
        if old_ref == new_ref:
            continue

        if ContentPage.objects.exclude(id=page.id).filter(slug=new_ref).count():
            setattr(
                page,
                f"name_{settings.MODELTRANSLATION_DEFAULT_LANGUAGE}",
                f"{page.name}-{str(page.id)}"
            )
            new_ref = get_prefixed_slug(page, page.origin, "name")

        page.slug = new_ref
        page.save()

        for version in Version.objects.get_for_object(page):
            data = json.loads(version.serialized_data)
            data[0]["fields"]["slug"] = new_ref
            version.serialized_data = json.dumps(data)
            version.save()

        # Termlink replaces can be done immediately
        for termlink in TermLink.objects.filter(url__startswith=old_ref):
            for lang_code, _ in settings.LANGUAGES:
                link = getattr(termlink, f"url_{lang_code}", "")
                if link:
                    setattr(termlink, f"url_{lang_code}", link.replace(old_ref, new_ref))
            try:
                termlink.save()
            except Exception as e:
                print(termlink.url_fi)
                raise e

            for version in Version.objects.get_for_object(termlink):
                data = json.loads(version.serialized_data)
                for lang_code, _ in settings.LANGUAGES:
                    link = data[0]["fields"].get(f"url_{lang_code}")
                    if link:
                        data[0]["fields"][f"url_{lang_code}"] = link.replace(old_ref, new_ref)
                version.serialized_data = json.dumps(data)
                version.save()

        # dl tag
        old_dl_tag = f"[!dl={old_ref}!]"
        new_dl_tag = f"[!dl={new_ref}!]"

        # assessment tag
        old_as_tag = f"<!assessment={old_ref}>"
        new_as_tag = f"<!assessment={new_ref}>"

        # link tags
        old_link_tag = f"[[{old_ref}"
        new_link_tag = f"[[{new_ref}"

        old_emb_tag = f"<!page={old_ref}>"
        new_emb_tag = f"<!page={new_ref}>"

        tags = [
            (old_dl_tag, new_dl_tag),
            (old_as_tag, new_as_tag),
            (old_emb_tag, new_emb_tag),
            (old_link_tag, new_link_tag)
        ]
        all_replaces.update(tags)

    term_replaces = defaultdict(dict)
    term_keys = []

    # Term slug replacements
    print("    Preparing prefixed term slugs")
    for term in Term.objects.all():
        for lang_code, _ in settings.LANGUAGES:
            lang_name = getattr(term, f"name_{lang_code}", "")
            if not lang_name:
                continue

            old_tag = f"[!term={lang_name}!]"
            new_tag = f"[!term={term.slug}!]"
            term_replaces[term.origin.prefix][old_tag] = new_tag
            term_keys.append(re.escape(old_tag))


    # Calendar slug replacements
    print("    Preparing prefixed calendar slugs")
    for calendar in Calendar.objects.all():
        old_tag = f"<!calendar={calendar.name}>"
        new_tag = f"<!calendar={calendar.slug}>"
        all_replaces[old_tag] = new_tag

    File = apps.get_model("courses", "File")
    Image = apps.get_model("courses", "Image")
    VideoLink = apps.get_model("courses", "VideoLink")

    print("    Preparing prefixed file slugs")
    for mediafile in File.objects.all():
        old_ref = mediafile.name
        new_ref = mediafile.slug

        old_emb_tag = f"<!file={old_ref}"
        new_emb_tag = f"<!file={new_ref}"

        old_script_tag = f"script={old_ref}"
        new_script_tag = f"script={new_ref}"

        old_style_tag = f"style={old_ref}"
        new_style_tag = f"style={new_ref}"

        old_flink = f"[[file:{old_ref}"
        new_flink = f"[[file:{new_ref}"

        tags = [
            (old_emb_tag, new_emb_tag),
            (old_script_tag, new_script_tag),
            (old_style_tag, new_style_tag),
            (old_flink, new_flink),
        ]
        all_replaces.update(tags)

    print("    Preparing prefixed image slugs")
    for image in Image.objects.all():
        old_ref = image.name
        new_ref = image.slug

        old_emb_tag = f"<!image={old_ref}"
        new_emb_tag = f"<!image={new_ref}"
        all_replaces[old_emb_tag] = new_emb_tag

    keys = [re.escape(key) for key in sorted(all_replaces, key=len, reverse=True)]

    pattern = re.compile("|".join(keys + term_keys))

    paginator = Paginator(ContentPage.objects.all(), 10)

    print("    Replacing slugs in content")
    for page in paginator.page_range:
        print(f"    Processing page {page} / {paginator.num_pages}")

        for container in paginator.page(page).object_list.iterator():

            def key_replace(matchobj):
                try:
                    return all_replaces[matchobj.group(0)]
                except KeyError:
                    prefix = container.origin and container.origin.prefix
                    return term_replaces[prefix].get(
                        matchobj.group(0), "null-missing-term"
                    )

            for lang_code, _ in settings.LANGUAGES:
                content = getattr(container, f"content_{lang_code}", "")
                content = pattern.sub(key_replace, content)
                setattr(container, f"content_{lang_code}", content)
            container.save()

            for version in Version.objects.get_for_object(container):
                data = json.loads(version.serialized_data)
                for lang_code, _ in settings.LANGUAGES:
                    content = data[0]["fields"].get(f"content_{lang_code}", "")
                    content = pattern.sub(key_replace, content)
                    data[0]["fields"][f"content_{lang_code}"] = content
                version.serialized_data = json.dumps(data)
                version.save()


def patch_media(queryset):
    for media_obj in queryset:
        for ver in Version.objects.get_for_object(media_obj):
            if not ver.field_dict.get("slug"):
                media_ver = (
                    ver.revision.version_set.get_queryset().get(content_type__model="coursemedia")
                )
                data = json.loads(media_ver.serialized_data)
                data[0]["fields"]["origin"] = media_obj.origin_id
                data[0]["fields"]["slug"] = media_obj.slug
                media_ver.serialized_data = json.dumps(data)
                media_ver.save()


def patch_archived_slugs(apps, schema_editor):
    File = apps.get_model("courses", "file")
    Image = apps.get_model("courses", "image")
    VideoLink = apps.get_model("courses", "videolink")

    patch_media(File.objects.all())
    patch_media(Image.objects.all())
    patch_media(VideoLink.objects.all())



class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_courseinstance_ws_server'),
    ]

    operations = [
        migrations.RunPython(guess_origins),
        migrations.RunPython(refactor_slugs),
        migrations.RunPython(patch_archived_slugs),
    ]
