# Generated by Django 5.2.5 on 2025-11-17 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_refactor_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinstance',
            name='ws_server',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.URLValidator(schemes=['ws', 'wss', 'http', 'https'])], verbose_name='WebSocket server address.'),
        ),
        migrations.AlterUniqueTogether(
            name='termalias',
            unique_together={('term', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='termlink',
            unique_together={('term', 'url')},
        ),
        migrations.AlterUniqueTogether(
            name='termtab',
            unique_together={('term', 'title')},
        ),
    ]
