# Generated by Django 5.2.5 on 2025-11-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_alter_courseinstance_ws_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileexercisesettings',
            name='answer_filename',
            field=models.CharField(blank=True, default='', help_text='Required for tasks where answer mode is TEXT. For FILE, submitted file is renamed to this name unless multiple files are returned. For multiple files this does nothing.', max_length=32, verbose_name='Filename to use for the answer'),
            preserve_default=False,
        ),
    ]
