# Generated by Django 5.2.5 on 2025-11-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_fileexercisesettings_answer_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='lexer',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Set lexer manually to'),
        ),
    ]
