# Generated by Django 5.2.5 on 2025-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_file_lexer'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='heading_level',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='Date heading level'),
            preserve_default=False,
        ),
    ]
