# Generated by Django 5.2.5 on 2026-01-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_evaluation_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskcompletion',
            name='state',
            field=models.CharField(choices=[('unanswered', 'The task has not been answered yet'), ('correct', 'The task has been answered correctly'), ('incorrect', 'The task has not been answered correctly'), ('credited', 'The task has been credited by completing another task'), ('submitted', 'An answer has been submitted, awaiting assessment'), ('rebsubmitted', 'A new answer answer has been submitted'), ('ongoing', 'The task has been started')], max_length=16),
        ),
    ]
