# Generated by Django 5.2.5 on 2026-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_alter_termlink_url_alter_termlink_url_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkboxexerciseanswer',
            name='weight',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='correct_threshold',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
        ),
    ]
