# Generated by Django 5.2.5 on 2026-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_checkboxexerciseanswer_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddedlink',
            name='answer_limit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Limit number of allowed attempts to'),
        ),
        migrations.AddField(
            model_name='embeddedlink',
            name='correct_threshold',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=8),
        ),
        migrations.AddField(
            model_name='embeddedlink',
            name='default_points',
            field=models.DecimalField(decimal_places=5, default=1, help_text='The default points a user can gain by finishing this exercise correctly', max_digits=8),
        ),
        migrations.AddField(
            model_name='embeddedlink',
            name='delayed_evaluation',
            field=models.BooleanField(default=False, verbose_name='This exercise is not immediately evaluated'),
        ),
        migrations.AddField(
            model_name='embeddedlink',
            name='group_submission',
            field=models.BooleanField(default=False, verbose_name='Answers can be submitted as a group'),
        ),
        migrations.AddField(
            model_name='embeddedlink',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='Required to complete course'),
        ),
        migrations.AddField(
            model_name='embeddedlink',
            name='manually_evaluated',
            field=models.BooleanField(default=False, verbose_name='This exercise is evaluated by hand'),
        ),
    ]
