# Generated by Django 5.2.5 on 2026-03-27 12:48

from django.db import migrations

def move_attributes(apps, schema_editor):
    EmbeddedLink = apps.get_model("courses", "embeddedlink")
    ContentPage = apps.get_model("courses", "contentpage")

    moved_fields = [
        "answer_limit",
        "correct_threshold",
        "default_points",
        "delayed_evaluation",
        "group_submission",
        "manually_evaluated",
    ]
    for page in ContentPage.objects.all():
        for link in EmbeddedLink.objects.filter(embedded_page=page):
            for field in moved_fields:
                setattr(link, field, getattr(page, field))

            link.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_embeddedlink_answer_limit_and_more'),
    ]

    operations = [
        migrations.RunPython(move_attributes)
    ]
