# Generated by Django 5.2.5 on 2026-04-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_move_attributes_to_embed_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpage',
            name='access_count',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='answer_limit',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='ask_collaborators',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='correct_threshold',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='default_points',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='delayed_evaluation',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='evaluation_group',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='group_submission',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='manually_evaluated',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='tags',
        ),
    ]
