# Generated by Django 5.2.5 on 2026-04-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_remove_contentpage_access_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpage',
            name='content_type',
            field=models.CharField(default='LECTURE', max_length=28),
        ),
    ]
