# Generated by Django 5.2.5 on 2026-04-16 14:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_alter_contentpage_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedlink',
            name='correct_threshold',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Marked as a quotient, defaults to 1 indicating fully completed', max_digits=8, validators=[django.core.validators.MaxValueValidator(Decimal('1'))], verbose_name='Amount of completion required to mark this task correct'),
        ),
        migrations.AlterField(
            model_name='embeddedlink',
            name='default_points',
            field=models.DecimalField(decimal_places=5, default=1, help_text='Amount of points a user can gain by finishing this exercise correctly in this course instance', max_digits=8, verbose_name='Point value'),
        ),
    ]
