# Generated by Django 5.2.5 on 2026-04-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_embeddedlink_correct_threshold_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gradethreshold',
            unique_together={('instance', 'grade')},
        ),
    ]
