# Generated by Django 5.2.5 on 2026-04-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_alter_embeddedlink_correct_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgraph',
            name='visibility',
            field=models.CharField(choices=[('both', 'Always visible'), ('exam-only', 'Only visible in Exam Mode'), ('no-exam', 'Not visible in Exam Mode')], default='both', max_length=16),
        ),
    ]
