# Generated by Django 5.2.5 on 2026-05-20 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_alter_gradethreshold_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendardate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='meeting_calendar',
            field=models.BooleanField(default=True, help_text="Meeting calendar reservations will show up in the host's personal calendar.", verbose_name='Is a meeting calendar'),
        ),
    ]
