# Generated by Django 6.0.6 on 2026-06-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_calendardate_created_by_calendarnotificationsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='termalias',
            unique_together={('term', 'name_fi')},
        ),
        migrations.AlterUniqueTogether(
            name='termlink',
            unique_together={('term', 'url_fi')},
        ),
        migrations.AlterUniqueTogether(
            name='termtab',
            unique_together={('term', 'title_fi')},
        ),
        migrations.AddField(
            model_name='contentgraph',
            name='visibility',
            field=models.CharField(choices=[('both', 'Always visible'), ('exam-only', 'Only visible in Exam Mode'), ('no-exam', 'Not visible in Exam Mode')], default='both', max_length=16),
        ),
    ]
