# Generated by Django 6.0.6 on 2026-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_calendardate_created_by_calendarnotificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='contentpage',
            unique_together={('name', 'origin'), ('name_en', 'origin'), ('name_fi', 'origin')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('origin', 'name'), ('origin', 'name_en'), ('origin', 'name_fi')},
        ),
        migrations.AlterUniqueTogether(
            name='termalias',
            unique_together={('term', 'name'), ('term', 'name_en'), ('term', 'name_fi')},
        ),
        migrations.AlterUniqueTogether(
            name='termlink',
            unique_together={('term', 'url'), ('term', 'url_en'), ('term', 'url_fi')},
        ),
        migrations.AlterUniqueTogether(
            name='termtab',
            unique_together={('term', 'title'), ('term', 'title_en'), ('term', 'title_fi')},
        ),
    ]
