# Generated by Django 5.2.5 on 2026-04-27 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_calendardate_created_by_calendarnotificationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgraph',
            name='visibility',
            field=models.CharField(choices=[('both', 'Always visible'), ('exam-only', 'Only visible in Exam Mode'), ('no-exam', 'Not visible in Exam Mode')], default='both', max_length=16),
        ),
    ]
