# Generated by Django 5.2.5 on 2026-05-29 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_contentgraph_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseInstanceExamWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Exam window start time')),
                ('end_time', models.DateTimeField(verbose_name='Exam window end time')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
            ],
        ),
    ]
