# Generated by Django 5.2.15 on 2026-08-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedlink',
            name='embedded_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='embedlink', to='courses.contentpage'),
        ),
        migrations.AlterField(
            model_name='embeddedlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentlink', to='courses.contentpage'),
        ),
    ]
