# Generated by Django 5.2.15 on 2026-08-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddedlink',
            name='embedded_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='embedlink', to='courses.contentpage'),
        ),
        migrations.AlterField(
            model_name='embeddedlink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentlink', to='courses.contentpage'),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textfieldexerciseanswer',
            name='comment_fi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseInstanceExamWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Exam window start time')),
                ('end_time', models.DateTimeField(verbose_name='Exam window end time')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
            ],
        ),
    ]
