# Generated by Django 6.1 on 2026-09-15 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_embeddedlink_embedded_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentgraph',
            name='visibility',
            field=models.CharField(choices=[('both', 'Always visible'), ('exam-only', 'Only visible in Exam Mode'), ('no-exam', 'Not visible in Exam Mode')], default='both', max_length=16),
        ),
        migrations.CreateModel(
            name='CourseInstanceExamWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Exam window start time')),
                ('end_time', models.DateTimeField(verbose_name='Exam window end time')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
            ],
        ),
    ]
