# Generated by Django 5.0.6 on 2025-05-14 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0028_textfieldwidgetsettings_content_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="XtermWidgetSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rows",
                    models.PositiveSmallIntegerField(
                        default=20,
                        help_text="Number of rows in the terminal view (determines widget height)",
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.contentpage",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.courseinstance",
                    ),
                ),
            ],
        ),
    ]
