# Generated by Django 5.2.1 on 2025-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_textfieldwidgetsettings_unique_together_and_more'),
        ('task_ws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xtermwidgetsettings',
            name='key_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='xtermwidgetsettings',
            name='content',
        ),
        migrations.AlterUniqueTogether(
            name='xtermwidgetsettings',
            unique_together={('key_slug', 'instance')},
        ),
    ]
