# Generated by Django 5.2.1 on 2025-06-10 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_alter_textfieldwidgetsettings_unique_together_and_more'),
        ('task_ws', '0002_alter_xtermwidgetsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurtleWidgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_slug', models.SlugField(blank=True, max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
            ],
            options={
                'unique_together': {('key_slug', 'instance')},
            },
        ),
    ]
