# Generated by Django 5.2.5 on 2025-09-01 15:53

from django.db import migrations
from utils.management import get_prefixed_slug

def refactor_data(apps, schema_editor):
    XtermWidgetSettings = apps.get_model("task_ws", "xtermwidgetsettings")
    TurtleWidgetSettings = apps.get_model("task_ws", "turtlewidgetsettings")
    for model in [XtermWidgetSettings, TurtleWidgetSettings]:
        for model_inst in model.objects.all():
            model_inst.course = model_inst.instance.course
            model_inst.name = model_inst.key_slug
            model_inst.slug = get_prefixed_slug(
                model_inst, model_inst.course, "name", translated=False
            )
            if not model.objects.filter(
                course=model_inst.course, slug=model_inst.slug
            ).exists():
                model_inst.save()
            else:
                model_inst.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('task_ws', '0004_alter_turtlewidgetsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(refactor_data)
    ]
