# Generated by Django 5.2.5 on 2025-09-01 15:53

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_ws', '0005_migrate_widget_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turtlewidgetsettings',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turtlewidgetsettings',
            name='name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turtlewidgetsettings',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xtermwidgetsettings',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xtermwidgetsettings',
            name='name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xtermwidgetsettings',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='turtlewidgetsettings',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='turtlewidgetsettings',
            name='key_slug',
        ),
        migrations.RemoveField(
            model_name='xtermwidgetsettings',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='xtermwidgetsettings',
            name='key_slug',
        ),
    ]
