# Generated by Django 6.1 on 2026-09-15 09:27

import django.db.models.deletion
import utils.management
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        ('task_ws', '0006_finalize_widget_refactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SQLWidgetSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
            bases=(models.Model, utils.management.ExportImportMixin),
        ),
    ]
