# Generated by Django 5.2.1 on 2025-06-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0001_initial'),
        ('courses', '0029_alter_contentpage_embedded_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acewidgetsettings',
            name='base_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.file'),
        ),
    ]
