# Generated by Django 5.2.1 on 2025-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0002_acewidgetsettings_base_file'),
        ('courses', '0030_alter_textfieldwidgetsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acepluswidgetsettings',
            name='key_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='acewidgetsettings',
            name='key_slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='acepluswidgetsettings',
            name='content',
        ),
        migrations.RemoveField(
            model_name='acewidgetsettings',
            name='content',
        ),
        migrations.AlterUniqueTogether(
            name='acepluswidgetsettings',
            unique_together={('key_slug', 'instance')},
        ),
        migrations.AlterUniqueTogether(
            name='acewidgetsettings',
            unique_together={('key_slug', 'instance')},
        ),
    ]
