# Generated by Django 5.2.5 on 2025-09-01 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0003_alter_acepluswidgetsettings_unique_together_and_more'),
        ('courses', '0031_alter_textfieldwidgetsettings_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acepluswidgetsettings',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='acewidgetsettings',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acepluswidgetsettings',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acepluswidgetsettings',
            name='name',
            field=models.CharField(default='tba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acepluswidgetsettings',
            name='slug',
            field=models.SlugField(default='tba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acewidgetsettings',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acewidgetsettings',
            name='name',
            field=models.CharField(default='tba', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acewidgetsettings',
            name='slug',
            field=models.SlugField(default='tba', max_length=255),
            preserve_default=False,
        ),
    ]
