# Generated by Django 5.2.5 on 2025-11-07 12:10
import re

from django.conf import settings
from django.db import migrations

def refactor_ace(apps, schema_editor):
    AcePlusWidgetSettings = apps.get_model("ace", "acepluswidgetsettings")
    ContentPage = apps.get_model("courses", "contentpage")

    all_replaces = {}

    for editor in AcePlusWidgetSettings.objects.all():
        old_tag = f"<!aceplus={editor.name}>"
        new_tag = f"<!aceplus={editor.slug}>"
        all_replaces[old_tag] = new_tag

    keys = [re.escape(key) for key in sorted(all_replaces, key=len, reverse=True)]
    pattern = re.compile("|".join(keys))

    def key_replace(matchobj):
        return all_replaces[matchobj.group(0)]

    paginator = Paginator(ContentPage.objects.all(), 10)

    for page in paginator.page_range:
        print(f"Processing page {page} / {paginator.num_pages}")

        for container in paginator.page(page).object_list.iterator():
            for lang_code, _ in settings.LANGUAGES:
                content = getattr(container, f"content_{lang_code}", "")
                content = pattern.sub(key_replace, content)
                setattr(container, f"content_{lang_code}", content)
            container.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0006_finalize_widget_refactor'),
    ]

    operations = [
        migrations.RunPython(refactor_ace)
    ]
