# Generated by Django 5.2.5 on 2025-11-18 09:30

import django.db.models.deletion
import utils.management
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ace', '0008_acepluslink'), ('ace', '0009_alter_acepluslink_unique_together_acepluslink_parent_and_more')]

    dependencies = [
        ('ace', '0007_refactor_ace'),
        ('courses', '0036_alter_courseinstance_ws_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcePlusLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_slug', models.CharField(max_length=255)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.contentpage')),
            ],
            options={
                'unique_together': {('widget_slug', 'instance', 'parent')},
            },
            bases=(models.Model, utils.management.ExportImportMixin),
        ),
    ]
