# Generated by Django 5.2.5 on 2025-11-17 15:21

from django.conf import settings
from django.db import migrations

from courses.markupparser import LinkParser
from utils.archive import get_single_archived

def create_aceplus_links(apps, schema_editor):
    ContentPage = apps.get_model("courses", "contentpage")
    ContentGraph = apps.get_model("courses", "contentgraph")
    CourseInstance = apps.get_model("courses", "courseinstance")
    EmbeddedLink = apps.get_model("courses", "embeddedlink")
    AcePlusLink = apps.get_model("ace", "acepluslink")

    for instance in CourseInstance.objects.all():
        instance_links = []
        cgs = instance.contentgraph_set.get_queryset()
        embeds = instance.embeddedlink_set.get_queryset()

        def parse_links(page):
            parser = LinkParser()
            content = getattr(page, f"content_{lang_code}", "")
            links = parser.parse(content)
            return links["aceplus"]


        for cg in cgs:
            page_links = set()
            for lang_code, __ in settings.LANGUAGES:
                if cg.revision is None:
                    page = cg.content
                else:
                    page = get_single_archived(cg.content, cg.revision)

                page_links.update(parse_links(page))
            instance_links.append((page, page_links))

        for parent, links in instance_links:
            for link_slug in links:
                link_obj = AcePlusLink(
                    widget_slug=link_slug,
                    instance=instance,
                    parent_id=parent.id,
                )
                link_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0008_acepluslink'),
    ]

    operations = [
        migrations.RunPython(create_aceplus_links)
    ]
