# Generated by Django 5.2.15 on 2026-08-03 15:01

import json
import re
from django.conf import settings
from django.core.paginator import Paginator
from django.db import migrations
from reversion.models import Version


def refactor_ace(apps, schema_editor):
    AcePlusWidgetSettings = apps.get_model("ace", "acepluswidgetsettings")
    ContentPage = apps.get_model("courses", "contentpage")

    all_replaces = {}

    for editor in AcePlusWidgetSettings.objects.all():
        old_tag = f"<!aceplus={editor.name}>"
        new_tag = f"<!aceplus={editor.slug}>"
        all_replaces[old_tag] = new_tag

    keys = [re.escape(key) for key in sorted(all_replaces, key=len, reverse=True)]
    pattern = re.compile("|".join(keys))

    def key_replace(matchobj):
        return all_replaces[matchobj.group(0)]

    paginator = Paginator(ContentPage.objects.all(), 10)

    for page in paginator.page_range:
        print(f"Processing page {page} / {paginator.num_pages}")

        for container in paginator.page(page).object_list.iterator():
            for version in Version.objects.get_for_object(container):
                data = json.loads(version.serialized_data)
                for lang_code, _ in settings.LANGUAGES:
                    content = data[0]["fields"].get(f"content_{lang_code}", "")
                    content = pattern.sub(key_replace, content)
                    data[0]["fields"][f"content_{lang_code}"] = content
                version.serialized_data = json.dumps(data)
                version.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ace', '0010_create_aceplus_links'),
    ]

    operations = [
        migrations.RunPython(refactor_ace)
    ]
