# Generated by Django 5.2.15 on 2026-08-13 15:07

import django.db.models.deletion
import utils.management
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTask',
            fields=[
            ],
            options={
                'verbose_name': 'exam task',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('courses.contentpage',),
        ),
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='examtask.examtask')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseinstance')),
            ],
            bases=(models.Model, utils.management.ExportImportMixin),
        ),
        migrations.CreateModel(
            name='ExamTaskToExerciseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='courses.contentpage')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='examtask.examtasksettings')),
            ],
            options={
                'unique_together': {('settings', 'exercise')},
            },
            bases=(models.Model, utils.management.ExportImportMixin),
        ),
        migrations.AddField(
            model_name='examtasksettings',
            name='task_pool',
            field=models.ManyToManyField(related_name='task_pool', through='examtask.ExamTaskToExerciseLink', through_fields=('settings', 'exercise'), to='courses.contentpage'),
        ),
        migrations.CreateModel(
            name='ExamTaskChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examtask.examattempt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examtask.examtasktoexerciselink')),
            ],
        ),
        migrations.AddField(
            model_name='examtasksettings',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='task', to='examtask.examtask'),
        ),
        migrations.AlterUniqueTogether(
            name='examtasksettings',
            unique_together={('instance', 'task')},
        ),
    ]
