# Generated by Django 5.2.15 on 2026-08-13 15:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        ('examtask', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamAttempt',
            new_name='ExamTaskAttempt',
        ),
    ]
