# Generated by Django 5.2.15 on 2026-08-18 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        ('examtask', '0002_rename_examattempt_examtaskattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examtaskchoice',
            unique_together={('user', 'attempt')},
        ),
        migrations.AddField(
            model_name='examtaskchoice',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.contentpage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examtaskattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='examtaskchoice',
            name='task',
        ),
    ]
