# Generated by Django 5.2.15 on 2026-08-19 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        ('examtask', '0003_alter_examtaskchoice_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExamTaskAnswer',
            fields=[
                ('useranswer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.useranswer')),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examtask.examtask')),
                ('task_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exam_proxy_answer', to='courses.useranswer')),
            ],
            bases=('courses.useranswer',),
        ),
    ]
