# Generated by Django 5.2.15 on 2026-08-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        ('examtask', '0004_userexamtaskanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtaskattempt',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_parent', to='courses.contentpage'),
        ),
    ]
