# Generated by Django 5.2.15 on 2026-08-19 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_alter_contentpage_unique_together_and_more'),
        ('examtask', '0005_examtaskattempt_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtaskattempt',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_examtask_attempt_set', to='courses.contentpage'),
        ),
        migrations.AlterField(
            model_name='examtasksettings',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='examtask.examtask'),
        ),
    ]
