# Generated by Django 5.2.15 on 2026-08-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examtask', '0006_alter_examtaskattempt_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtaskchoice',
            name='opened',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='examtasksettings',
            name='avoid_same',
            field=models.BooleanField(default=False, verbose_name='Avoid assigning same task'),
        ),
    ]
