# Generated by Django 5.2.15 on 2026-08-24 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_embeddedlink_embedded_page_and_more'),
        ('examtask', '0007_examtaskchoice_opened_examtasksettings_avoid_same'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtasktoexerciselink',
            name='embedlink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.embeddedlink'),
        ),
    ]
