# Generated by Django 5.2.15 on 2026-08-24 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_alter_embeddedlink_embedded_page_and_more'),
        ('examtask', '0008_examtasktoexerciselink_embedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examtaskchoice',
            name='exercise',
        ),
        migrations.AlterUniqueTogether(
            name='examtasktoexerciselink',
            unique_together={('settings', 'embedlink')},
        ),
        migrations.AddField(
            model_name='examtaskchoice',
            name='embedlink',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.embeddedlink'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examtasksettings',
            name='task_pool',
            field=models.ManyToManyField(related_name='task_pool', through='examtask.ExamTaskToExerciseLink', through_fields=('settings', 'embedlink'), to='courses.embeddedlink'),
        ),
        migrations.AlterField(
            model_name='examtasktoexerciselink',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examtask.examtasksettings'),
        ),
        migrations.RemoveField(
            model_name='examtasktoexerciselink',
            name='exercise',
        ),
    ]
